# Site settings
title: Learn ReactJS
tag_text: Learn ReactJS
description: A list that includes some resources and tutorials to help you learn the wonderful ReactJS library.

# Build settings
markdown: kramdown
baseurl: /react_blog
exclude: ["README.md"]
sass:
  style: compressed
